# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Harpo Jaeger
tagline:          ''
description:      'I write about politics, organizing and two-stroke engines.'
url:              http://harpojaeger.com
baseurl:          '/'
paginate:         10
paginate_path:    "/posts/page:num"

author:
  name:           'Harpo Jaeger'
  url:            https://twitter.com/harpojaeger

# Custom vars
# version:          1.0.0

# github:
#  repo:           https://github.com/poole/lanyon
encoding:           utf-8