# Site settings
title: harpojaeger.com
email: me@harpojaeger.com
description: "Harpo Jaeger's web site!"
baseurl: ""
url: "http://harpojaeger.com"
twitter_username: harpojaeger
#github_username:  harpojaeger

# Build settings
markdown: kramdown
permalink: pretty
