# Site settings
title: harpojaeger.com
email: me@harpojaeger.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://harpojaeger.com"
twitter_username: harpojaeger
#github_username:  harpojaeger

# Build settings
markdown: kramdown
permalink: pretty
