# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Harpo Jaeger
tagline:          'Third-wave pluralist & Senior Leftwing Jewish Malcontent'
description:      'I write about politics, organizing and two-stroke engines.'
url:              http://harpojaeger.github.io
baseurl:          '/'
paginate:         10

author:
  name:           'Harpo Jaeger'
  url:            https://twitter.com/harpojaeger

# Custom vars
# version:          1.0.0

# github:
#  repo:           https://github.com/poole/lanyon
