# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate, jekyll-seo-tag]

# Permalinks
permalink:        pretty

# Setup
title:            Harpo Jaeger
tagline:          'dot com'
description:      'I write about politics, organizing and two-stroke engines.'
url:              'http://harpojaeger.com'
baseurl:          '/'
paginate:         20
paginate_path:    "/posts/page:num"
exclude:          ['assets/scripts/newpost']

twitter:
  username: harpojaeger

# Custom vars
# version:          1.0.0

# github:
#  repo:           https://github.com/poole/lanyon
encoding:           utf-8
