# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            harpojaeger.com
tagline:          '"Senior leftwing Jewish malcontent"'
description:      'Politics, organizing & two-stroke engines.'
url:              http://harpojaeger.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Harpo Jaeger'
  url:            https://twitter.com/harpojaeger

# Custom vars
# version:          1.0.0

# github:
#  repo:           https://github.com/poole/lanyon
