# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate, jekyll-seo-tag]

# Permalinks
permalink:        pretty

# Setup
title:            Harpo Jaeger
tagline:          'dot com'
description:      'Politics, organizing and ham radio.'
url:              'http://www.harpojaeger.com'
baseurl:          ''
paginate:         20
paginate_path:    "/posts/page:num"
exclude:          ['assets/scripts/newpost']

twitter:
  username: harpojaeger

# Custom vars
# version:          1.0.0

# github:
#  repo:           https://github.com/poole/lanyon
encoding:           utf-8
